name: CI 
#name of the file

on: #kaha workflow trigger krega
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test: #ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies #pip upgrade
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          coverage run -m pytest
          coverage report
